name: Setup development environment

on:
  pull_request:
    branches:
      - 'master'
    types: [opened, synchronize, closed]

jobs:
  run-dev:
    runs-on: ubuntu-latest
    env:
      ENV: dev

    steps:
      - uses: actions/checkout@v1
      - name: echo
        run: |
          echo ${ENV}
      - name: echo merged
        if: github.event.pull_request.merged == true
        run: |
          echo ${ENV}
